### ISSUE TITLE
No such file or directory.

### ISSUE THREAD

**Issue by nguyenrom** [lesaff/serverpilot-letsencrypt#1]
> We're almost done here. Restarting nginx...
> Restarting nginx-sp: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/abc.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/abc.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
> nginx-sp.

**Comment by nguyenrom** [comment]
I've found the cause, I dont added domain name to server before install SSL. I apologize for the disturbance.

**Comment by lesaff** [comment]
No worries. Make sure to remove the scheduled event in your crontab.
