### ISSUE TITLE
"You are running with an old copy of letsencrypt-auto"

### ISSUE THREAD

**Issue by lindseydiloreto** [lesaff/serverpilot-letsencrypt#11]
Hi Rudy,

Just got this message when trying to re-install the cert for a site...

<img width="538" alt="screen shot 2016-08-14 at 1 28 21 pm" src="https://cloud.githubusercontent.com/assets/5309692/17651839/5c26f326-6223-11e6-89de-9ca3a7ebbcbd.png">

Is this something that has already been addressed?

**More info...** This is an old installation of the script. One of my sites became "unsecure", so I wiped the cron & `.ssl.conf` file, and re-initialized the cert. I did grab the latest version of the script, but I know it didn't uninstall the original instance of `letsencrypt`.

Let me know if you have any questions, I'd be happy to provide more information.

**Comment by lesaff** [comment]
let me update the script to grab the new certbot instead of the old letsencrypt repo. Thanks

**Comment by lindseydiloreto** [comment]
Sweet, sounds good.

**Comment by lesaff** [comment]
New version with the latest `certbot` script is available on the master branch now.

**Comment by lindseydiloreto** [comment]
Awesome, thanks!
