### ISSUE TITLE
Error restarting ngnix

### ISSUE THREAD

**Issue by knynkwl** [lesaff/serverpilot-letsencrypt#12]
I get this error when trying to restart nginx. Also for what it's worth, when I run `sple.sh` again, it says:
**Let's Encrypt is not installed/found in your root folder. Would you like to install it?**

running Ubuntu 14.04.5 x64
I don't see any letsencrypt logs in `var/logs`
I dont see a folder `/etc/letsencrypt`

Also site went offline.

Error
```
Restarting nginx-sp: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/sitename.org/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/sitename.org/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx-sp.
```

**Comment by lesaff** [comment]
SSH to your server as root, cd to `/etc/nginx-sp/vhosts.d`
Delete the `<appname>.ssl.conf` that you were trying to add
Restart nginx.

**Comment by knynkwl** [comment]
The made the site work again but it's failing on install.

Errors:
`/usr/local/bin/sple.sh: line 104: /usr/local/bin/certbot-auto: No such file or directory`
 
and 

```
We're almost done here. Restarting nginx...
Restarting nginx-sp: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/67.205.143.104/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/67.205.143.104/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx-sp.
```

**Comment by lesaff** [comment]
Interesting. Looks like `sple.sh` is not installing certbot properly.

Login to your server as root
Type 
```
cd /usr/local/bin && wget https://dl.eff.org/certbot-auto
chmod a+x certbot-auto
```
and run `sple.sh` again

**Comment by knynkwl** [comment]
That installed it, but got the same error when it tries to restart ngnix.

```
We're almost done here. Restarting nginx...
Restarting nginx-sp: nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/67.205.143.104/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/67.205.143.104/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx-sp.
```

**Comment by lesaff** [comment]
I don't think you can register IP address to get letsencrypt certificate. Also, your domain name has to resolve to the correct IP that you use on your server before it can successfully sign a certificate.

**Comment by knynkwl** [comment]
Ah okay, I was trying to test before moving the DNS over to the new server but I guess I'll have to wait. Thanks!
