### ISSUE TITLE
Site Doesnt load

### ISSUE THREAD

**Issue by diegofba** [lesaff/serverpilot-letsencrypt#14]
Hi, I did everything as you said -got no errors- and my site has lost its connection and cannot access to wordpress (i didn't change http to https in options -i don't think this is the issue)
I'm using vultr Ubuntu 16.04 x64
Thanks in advance

**Comment by lesaff** [comment]
Most likely letsencrypt could not authenticate your domain name.

Follow the `if things go wrong` section in the readme to undo the ssl config.
