### ISSUE TITLE
./sple.sh throwing ./sple.sh: line 5: syntax error near unexpected token `newline', ./sple.sh: line 5: `<!DOCTYPE html>' errors

### ISSUE THREAD

**Issue by sam-suresh** [lesaff/serverpilot-letsencrypt#17]
When I run ./sple.sh 
I get the following error in console. 

./sple.sh: line 5: syntax error near unexpected token `newline'
./sple.sh: line 5: `<!DOCTYPE html>'

**Comment by lesaff** [comment]
Make sure you copy the script from the raw file. Looks like it's saving the html page.

Save it from here
https://raw.githubusercontent.com/lesaff/serverpilot-letsencrypt/master/sple.sh

**Comment by sam-suresh** [comment]
Solved thank you
