### ISSUE TITLE
Delete Let's Encrypt

### ISSUE THREAD

**Issue by Rivellio** [lesaff/serverpilot-letsencrypt#18]
Hello,

There should be a way to uninstall or remove this completely. If you ever stop using SSL or are looking to change to another certificate.

I would appreciate a guide on how to remove this from one of my sites. It's really a nice script but I'm thinking about switching on my CloudFlare cert.

**Comment by lesaff** [comment]
Follow https://github.com/lesaff/serverpilot-letsencrypt#if-things-go-wrong to remove it completely.
