### ISSUE TITLE
Multiple SSLs with Serverpilot & Digital Ocean

### ISSUE THREAD

**Issue by Nrddy** [lesaff/serverpilot-letsencrypt#19]
I have installed serverpilot on a digitalocean droplet everything works great. I have 2 wordpress sites runnin, I used your program to install the first ssl and the site works just fine. No issues... But when i install a second ssl for a second app. when its done I get connection refused. When I go and delete the .conf file for the new ssl that was created and restart the nginx everything works again. Any suggestions on what i need to do to get it to work?

Thanks

Update - I found the answer. My Dns hadn't fully resovled yet when I set the the ssl and that was kicking it to reject all connections.

**Comment by lesaff** [comment]
Glad you found out about your issue. 👍

**Comment by bertaveira** [comment]
I have the same problem. When I generate the ssl for the second app both stop working. I have no idea why. I have the domain for over 5 days so I think it's not a dns problem
