### ISSUE TITLE
renew bug

### ISSUE THREAD

**Issue by juriss** [lesaff/serverpilot-letsencrypt#21]
Upgrading certbot-auto 0.8.1 to 0.9.3...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
An unexpected error occurred:
Bug in pythondialog: expected an empty output from u'infobox', but got: u'Error opening terminal: unknown.\n'Please see the logfile 'certbot.log' for more details.

**Comment by lesaff** [comment]
Can you show me the steps until you get that error pls?

I couldn't replicate on my end.

**Comment by juriss** [comment]
It happened on automatic updates (one month before the expiry), this is from email notification.

Cron <root@mydomain> /root/letsencrypt/letsencrypt-auto certonly --renew-by-default --webroot -w /srv/users/serverpilot ......

**Comment by lesaff** [comment]
Try adding the following parameters to your cronjob
`--text --non-interactive`

It should look like this
```
0 1 1 */2 * /root/letsencrypt/letsencrypt-auto certonly --renew-by-default --text --non-interactive --webroot -w /srv/users/serverpilot/apps/<YOUR_APP_NAME>/public -d <YOUR_DOMAIN_NAME>
```

**Comment by juriss** [comment]
It looks like it works. Many thanks lesaff !

**Comment by lesaff** [comment]
No worries. The latest version of this script uses a much different system. Have a look
