### ISSUE TITLE
nginx needs a restart after running this script

### ISSUE THREAD

**Issue by xyzulu** [lesaff/serverpilot-letsencrypt#24]
I've tested this a few times and each time I had to manually restart nginx. I know a restart is in this script, but I've still found I need to do it again myself once the script completes. Maybe it's just me.. but I did test on 2 different u16.04 servers.

Nice script however..thanks for sharing

**Comment by miwilc** [comment]
https://github.com/lesaff/serverpilot-letsencrypt/blob/master/sple.sh#L202 its there
