### ISSUE TITLE
Two apps not working

### ISSUE THREAD

**Issue by monpac** [lesaff/serverpilot-letsencrypt#27]
Have you tried this script with 2 apps on the same server? The certificate seems to generate correctly but both apps stop working when the ssl.conf file is created. After I delete it, they both start working again. Didn't try creating 2 certificates for each app yet.

**Comment by lesaff** [comment]
I've tested and ran this script on a server with over 100 apps without any problem. 
What usually happens is when Let's Encrypt cannot verify one or more domain names requested.

**Comment by monpac** [comment]
@lesaff thanks! will try again then and try to debug the problem.
