### ISSUE TITLE
Nginx-sp Fails

### ISSUE THREAD

**Issue by sam-suresh** [lesaff/serverpilot-letsencrypt#29]
Running this installer now killing the FPM PHP and server stop working. 

Was working fine before this. 

Tested on new server, same. 

Ubuntu 16.04 x64

**Comment by lesaff** [comment]
Hmm, never heard/seen this issue before. Which Ubuntu are you using (16.x or 14.x)?

**Comment by sam-suresh** [comment]
Here is what log file says;

2017/02/07 15:37:34 [emerg] 9171#0: BIO_new_file("/etc/letsencrypt/live/domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/li$
2017/02/08 00:04:29 [emerg] 2814#0: BIO_new_file("/etc/letsencrypt/live/domain.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/l$

I also couldn't find /etc/letsencrypt directory. Running ./sple.sh still doesn't fix this. I have to remove ssl.conf.

**Comment by lesaff** [comment]
Did you mask your own domain and replaced it with `domain.com`?
If not, that's probably why it failed. Also, what version of Ubuntu are you using?

**Comment by sam-suresh** [comment]
Yes. I just masked the domain. Its on Ubuntu 16:04.

**Comment by sam-suresh** [comment]
Solved by running

`apt-get -f install`
`cd /usr/local/bin`
`./sple.sh`

**Comment by j2is** [comment]
Hey I have a similar issue but I haven't masked the domain, and nginx-sp fails, the fix by @sam-suresh hasn't worked. I'm running Ubuntu 16.04.3.
