### ISSUE TITLE
ENHANCEMENT: Restart NGINX after renewal of certs

### ISSUE THREAD

**Issue by caroseuk** [lesaff/serverpilot-letsencrypt#32]
Hey, just a quick one.

I  have just renewed my certs with the script. Works perfectly however I had to manualy restart nginx after the renewals for them to be picked up by the browser.. So it might be worth creating a separate script which can be executed by CRON instead of the suggested CRON line..

**Comment by oviliz** [comment]
Just add another cron line with `/etc/init.d/nginx reload` at your desired time (i.e. 5 minutes later after executing the script). To me the every 12 hours cron for the script is excessive while one every week it should be enough.

**Comment by caroseuk** [comment]
That could be done but it seems a bit of a shortcut, you would be restarting NGinx even if the renewal failed. If this was contained in a shell script, it could renew and then if renewals were successful, then reload/restart nginx.
