### ISSUE TITLE
Network Error (tcp_error) 

### ISSUE THREAD

**Issue by gissa** [lesaff/serverpilot-letsencrypt#33]
After installing SSL using sple.sh
my website can’t have accessed and showing this error message

Network Error (tcp_error) 

A communication error occurred: "Connection reset by peer"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team.
I have restarting ngix-sp  and power cycling vps via digitalocean dashboard but nothing work 

im using 512 MB Memory / 20 GB Disk / NYC1 - Ubuntu 16.04.2 x64

**Comment by lesaff** [comment]
This happens when one or more domain name is not recognized by Let's Encrypt yet

Follow this step by step to get your server back up again
https://github.com/lesaff/serverpilot-letsencrypt#if-things-go-wrong

**Comment by lesaff** [comment]
Here’s a quick test only command if you want to test whether your domain name is ready for LE SSL or not. Just replace `<app>` with your appname and `<domain.tld>` with your domain name.

Ubuntu 16.x
```
letsencrypt certonly --webroot -w /srv/users/serverpilot/apps/<app>/public -d <domain.tld> --test-cert
```

Ubuntu 14.x
```
certbot-auto certonly --webroot -w /srv/users/serverpilot/apps/<app>/public -d <domain.tld> --test-cert
```

**Comment by gissa** [comment]
Thankyou @lesaff , i forgot to create cname record for www.mydomain.com 

in fact, there is an error message when I install ssl , my bad :D 
thank you  , by the way are you from Indonesia ? because your name sound familiar to me ?

**Comment by lesaff** [comment]
You're welcome. Yes, born in Indonesia but grew up in Canada. You're Indonesian?

**Comment by gissa** [comment]
Yes, I'm from Bandung hehe
