### ISSUE TITLE
Brotli compression not enabled

### ISSUE THREAD

**Issue by Olsserik** [lesaff/serverpilot-letsencrypt#37]
Hi,
When using this (awesome) script it seems that it not enables Brotli compression. When using Serverpilot paid function they enable Brotli with HTTP/2.

Any clues on how to enable Brotli with this script?

**Comment by caroseuk** [comment]
As soon as SSL is enabled on the server brotli compression should be automatic.

I've just checked and assets from my site are showing with encoding of "br"

If your using Chrome, open the inspector and reload a page on your server. Select a style sheet (as an example) and it should say in the response headers:

content encoding: br

**Comment by Olsserik** [comment]
Hi,
Yes, that's exactly what I did, using chrome.
I get h2 - https - gzip - nginx

Have I done anything wrong in setup?

**Comment by Olsserik** [comment]
Wrong button...

**Comment by caroseuk** [comment]
Whats your domain?

**Comment by Olsserik** [comment]
It's a non-public (for now), can I send you PM?

**Comment by caroseuk** [comment]
sure send it to github@crose.co.uk

**Comment by Olsserik** [comment]
Sent!

**Comment by Olsserik** [comment]
@caroseuk fixed the issue.
I had AddOutputFilterByType DEFLATE in .htaccess. When gone it Brotlis like never before.
