### ISSUE TITLE
Auto-renewal cron

### ISSUE THREAD

**Issue by lindseydiloreto** [lesaff/serverpilot-letsencrypt#47]
At the end of the installation process, the script prompts you to set an auto-renewal cron...

    To enable auto-renewal, add the following to your crontab:
    0 */12 * * * /usr/local/bin/certbot-auto renew --quiet --no-self-upgrade

But on the [README](https://github.com/lesaff/serverpilot-letsencrypt/blob/master/README.md#schedule-auto-renewal) page of this repo, it says something slightly different...

    0 */12 * * * /usr/local/bin/certbot-auto renew --quiet --no-self-upgrade --post-hook "service nginx-sp reload"

Which one is preferred?

**Comment by caroseuk** [comment]
The readme one will Work best ☺️ I’ll send a PR to update the script!

**Comment by lindseydiloreto** [comment]
Awesome, thanks @caroseuk! Very helpful to know.

**Comment by slowmail** [comment]
The current readme.md says

For Ubuntu 16.04
`0 */12 * * * letsencrypt renew --post-hook "service nginx-sp reload"`

But, I'm getting the following output from cron, it appears the --post-hook is not recognized?

letsencrypt renew --post-hook "service nginx-sp reload"
> usage:
>   letsencrypt [SUBCOMMAND] [options] [-d domain] [-d domain] ...
> 
> The Let's Encrypt agent can obtain and install HTTPS/TLS/SSL certificates.  By
> default, it will attempt to use a webserver both for obtaining and installing
> the cert. Major SUBCOMMANDS are:
> 
>   (default) run        Obtain & install a cert in your current webserver
>   certonly             Obtain cert, but do not install it (aka "auth")
>   install              Install a previously obtained cert in a server
>   renew                Renew previously obtained certs that are near expiry
>   revoke               Revoke a previously obtained certificate
>   rollback             Rollback server configuration changes made during install
>   config_changes       Show changes made to server config during installation
>   plugins              Display information about installed plugins
> letsencrypt: error: unrecognized arguments: --post-hook service nginx-sp reload

**Comment by arabo11** [comment]
Yes, that's right. I'm getting "letsencrypt: error: unrecognized arguments: --post-hook service nginx-sp reload" too in Ubuntu 16.04.

**Comment by caroseuk** [comment]
It seems as though the script installs an old version of the letsencrypt software in Ubuntu 16.04. Which is what is causing this issue as it is missing those arguments.

In the meantime, theres a few different potential solutions:

[WORKAROUND - **Quick**]
1.) Change CRON on 16.04 to:
`0 */12 * * * letsencrypt renew && service nginx-sp reload`  

Obviously this will gracefully reload nginx wether the renewal was successful or not.

OR

[WORKAROUND - **Risky Untested**]
2.) You could attempt to install the latest certbot using the instructions at [https://certbot.eff.org/#ubuntuxenial-other](https://certbot.eff.org/#ubuntuxenial-other)

Then setting the CRON to run:
`certbot renew --post-hook "service nginx-sp reload"`

Ideally for future installs the script should be updated to cater for the latest version of Certbot from the Ubuntu PPA.

In the meantime, I will update the Readme.

**Comment by lindseydiloreto** [comment]
So wait, just to recap...

For **Ubuntu 14.04**, we can use this line, as newly updated in the docs...

    0 */12 * * * /usr/local/bin/certbot-auto renew --quiet --no-self-upgrade --post-hook "service nginx-sp reload"

And for **Ubuntu 16.04**, we can use this line...

    0 */12 * * * letsencrypt renew && service nginx-sp reload

I know you wrote two versions of the 16.04 line, I'm clearly gravitating towards the "safer" option. :wink:

Is that all correct?

**Comment by caroseuk** [comment]
Hey,

Yeah, this is what I think is the safer option for 16.04 as it uses an old version of letsencrypt.

Whereas the script installs the latest certbot-auto script for 14.04.

**Comment by lindseydiloreto** [comment]
Great, thanks @caroseuk!
