### ISSUE TITLE
Getting unexpected `newline`

### ISSUE THREAD

**Issue by j7an** [lesaff/serverpilot-letsencrypt#53]
Getting the following error when I try to run the script

```
root@ip-xxx-xx-xx-xxx:/usr/local/bin# ./sple.sh 
./sple.sh: line 7: syntax error near unexpected token `newline'
./sple.sh: line 7: `<!DOCTYPE html>'
```

**Comment by xyzulu** [comment]
Re-downloaded the file and tried again? Use:

`wget -O sple.sh https://raw.githubusercontent.com/lesaff/serverpilot-letsencrypt/master/sple.sh`
then..
`sudo chmod +x /usr/local/bin/sple.sh`
