### ISSUE TITLE
Error: connection refused

### ISSUE THREAD

**Issue by daviedR** [lesaff/serverpilot-letsencrypt#54]
Hi guys, I am very newbie about server configuration. I am currently running Ubuntu 14.04 on DigitalOcean and using Serverpilot.

I followed the instruction to install Let's Encrypt on one of my domain. When running the `sple.sh` script, I got an error like this:

```
Failed authorization procedure. mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mydomain.com/.well-known/acme-challenge/aw8TK32BOdF4l56PiTKnw_QLlcTwggpIYyu_BGL3UQ8: Connection refused
```

Can you explain why this error occured? How to fix this?

Big thanks!

**Comment by caroseuk** [comment]
Have you made sure to point your domain to your server (is it reachable to
the general public). If the ACME server cannot ping the domain to verify
it, it will give you that error.

**Comment by daviedR** [comment]
You can try davidrozando.com, it's currently pointed to ns1.digitalocean.com

**Comment by caroseuk** [comment]
The site doesn't appear to be up - "This site can’t be reached"

That is what the acme client will received which is why it is not working..

**Comment by daviedR** [comment]
I removed the `davidrozando.ssl.conf` on `/etc/nginx-sp/vhosts.d`. The domain should be up by now.

And then I tried `sple.sh` again, enter the System user name: `serverpilot` (is this right?)

But it failed with same error. So I just remove the ssl.conf file again.

**Comment by caroseuk** [comment]
Hmmm, make sure you are running the script as root and that you have both port 80 and 443 open on the firewall?

I've not used the script for a while now and its hard to debug without having access.

**Comment by daviedR** [comment]
Yes I am on root access right now. How to check whether port 443 is open or not? Or how to make port 443 open on DigitalOcean / ServerPilot?

Sorry I am super newbie on server configuration.

**Comment by caroseuk** [comment]
As root, type:

`ufw allow https`

That will open the port on Ubuntu.

**Comment by daviedR** [comment]
It returned this:

```
Skipping adding existing rule
Skipping adding existing rule (v6)
```

Hmm?

**Comment by caroseuk** [comment]
Looks like the port is indeed open. Hmmm, im stumped without having access to the server directly.

**Comment by caroseuk** [comment]
How long ago did you make the DNS changes? My last idea is that if it was within the last 24 hours, then the LetsEncrypt server may not be able to resolve you address yet..

**Comment by daviedR** [comment]
It's very old setup domain. Actually I want to use HTTPS for other domains, but decided to do experiment on the davidrozando.com first. So I can make sure the DNS is already propagated since long time ago.

Btw, I tried: `ufw status` and port 443 is on the list.

However when I checked using `netstat -tpln` and cannot find any port 443 in the list.

Hmm

**Comment by daviedR** [comment]
I think it's something on the config file created by free version of ServerPilot which doesn't include port 443 to be listened. I don't know where to change the configuration.

Maybe ServerPilot would automatically open port 443 only on paid plan.

**Comment by daviedR** [comment]
Nevermind, it's working now. Not sure what I did, but my previous attempt was successful.

Thanks guys!
