### ISSUE TITLE
The cron job schedule seems wrong

### ISSUE THREAD

**Issue by andporter** [lesaff/serverpilot-letsencrypt#6]
The current cron is:
"* 1 * */2 * $lefolder/letsencrypt-auto certonly --renew-by-default --webroot -w /srv/users/serverpilot/apps/$appname/public ${APPDOMAINLIST[@]}"

This will run every minute of the 1am hour every day of every other month.. like this:
2016-06-01 01:00:00 UTC
2016-06-01 01:01:00 UTC
2016-06-01 01:02:00 UTC
2016-06-01 01:03:00 UTC
2016-06-01 01:04:00 UTC
...

I think it should be:

"0 1 1 */2 * $lefolder/letsencrypt-auto certonly --renew-by-default --webroot -w /srv/users/serverpilot/apps/$appname/public ${APPDOMAINLIST[@]}"

which will run like this:
2016-06-01 01:00:00
2016-08-01 01:00:00
2016-10-01 01:00:00
2016-12-01 01:00:00
2017-02-01 01:00:00
...

This is an excellent script! Thank you

**Comment by lesaff** [comment]
Good catch, thx for spotting that. Let me push this changes
