### ISSUE TITLE
Subdomains and separate apps

### ISSUE THREAD

**Issue by daviedR** [lesaff/serverpilot-letsencrypt#63]
Hi,

I am using Serverpilot and have a separate app for my subdomain. For example:

Main app
- App name: `mydomain`
- Domains: `mydomain.com`, `www.mydomain.com`

Dev app
- App name: `mydomain-dev`
- Domains: `dev.mydomain.com`, `www.dev.mydomain.com`

In you bash script, we need to input the app name. For the dev app, should I create separate certificate (considering it's a different app on ServerPilot) OR use the main app certificate?

I tried to make separate certificate for `mydomain-dev`, but my serverpilot went down and I had to remove the `mydomain-dev.ssl.conf` file and reboot `nignx-sp` to get it working again.

Any idea?

**Comment by caroseuk** [comment]
www.dev.mydomain.com is not a valid URL so trying to create a certificate for that will more than likely fail?

I create separate apps for development domains.

when creating your certificate using the script, just enter the single domain dev.mydomain.com and within the app in SP remove the www.dev.mydomain.com domain from the SP control panel? Then try again

Just my thoughts. :)

**Comment by daviedR** [comment]
@caroseuk

Oh great! Yeah the `www.dev.mydomain.com` is the issue, the www subdomain is not registered as A DNS record on my server. I enter the `dev.mydomain.com` on the bash script and it works!

Thanks!
