### ISSUE TITLE
Will this work with Cloudflare enabled?

### ISSUE THREAD

**Issue by ankurshva** [lesaff/serverpilot-letsencrypt#64]
I use Cloudflare on my website. Will this work?

**Comment by lesaff** [comment]
Yes it should. I have a few sites on free Cloudflare account and so far so good.

**Comment by ankurshva** [comment]
It didn't work. Error 521. Even after deleting the conf file, Error 521 did not go!

**Comment by Dibbyo456** [comment]
@ankurshva When generating SSL disable Cloudflare first. Once you generated the SSL, you can use Cloudflare's Flexible or Full SSL, both will work fine.

**Comment by caroseuk** [comment]
You mean disable the Cloudflare SSL and use CloudFlare JUST for DNS. Then this script will work. I would also disable any caching/cdn features from within CloudFlare before you run the script.

The script will fail if you are using either the FREE Cloudflare SSL or paid version.

**Comment by Dibbyo456** [comment]
> You mean disable the Cloudflare SSL and use CloudFlare JUST for DNS

**Correct**. You have to use **Cloudflare DNS Only**.

**Comment by Salamander3** [comment]
hm i did it with cloudflare enabled and didn't notice any issue.

I was using flexible since i didn't have a cert, after using this script i was able to:
1) Use Full mode and full mode (sctrict)
2) Pause cloudflare and still serve http pages.

All fine on my end luckily.
