### ISSUE TITLE
Does this work with Ubuntu 18.04? 

### ISSUE THREAD

**Issue by ankurshva** [lesaff/serverpilot-letsencrypt#71]

**Comment by Nrddy** [comment]
I just updated my local copy of sple.sh swapped out all the 16.04 for 18.04 and it seemed to work just fine. However I am not a developer on this project so I am not sure if that is Proof that it works or not. but it did work for me.

**Comment by Dibbyo456** [comment]
@Nrddy Could you update the modified sple.sh in your fork?

**Comment by Dibbyo456** [comment]
@ankurshva You can use the [forked version of sple.sh which works for Ubuntu 18.04](https://github.com/Dibbyo456/serverpilot-letsencrypt)

**Comment by pixelbeatcreative** [comment]
I can confirm that it does NOT work on Ubuntu 18.04. :(  Any plans on updating the script?

**Comment by rehmatworks** [comment]
You can try https://github.com/rehmatworks/serverpilot-letsencrypt
