### ISSUE TITLE
syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by socialpreneur** [lesaff/serverpilot-letsencrypt#8]
I downloaded sple.sh using wget command, followed your instructions and executed sple.sh. However, following errors occur no matter how many times I try.

/usr/local/bin/sple.sh: line 5: syntax error near unexpected token `newline'
/usr/local/bin/sple.sh: line 5: `<!DOCTYPE html>'

I've done all the commands as root.

**Comment by lesaff** [comment]
Looks like you wget the wrong page. It should not have `html` tag in it.

try `wget https://raw.githubusercontent.com/lesaff/serverpilot-letsencrypt/master/sple.sh`
to get the raw script.

**Comment by lesaff** [comment]
@socialpreneur, are you still having this issue? If not, I will close this one.

Thx
