### ISSUE TITLE
Restarting nginx-sp: nginx: [warn] conflicting server name ".."  on 0.0.0.0:443, ignored

### ISSUE THREAD

**Issue by debpalash** [lesaff/serverpilot-letsencrypt#9]
getting this error 4 times after doing it for one of my existing wp site installaion. all site died.
wtf man?

why it does that?

**Comment by lesaff** [comment]
When you restart nginx-sp, it cycles through all of your nginx configuration. If one of them is not correct, it won't start nginx. That error (0.0.0.0:443), it looks like one of your domain names that you're trying to add to Let's Encrypt is not yet pointed to the right serverpilot IP. 

You can just remove the `appname.ssl.conf` from `/etc/nginx-sp/vhosts.d`
See https://github.com/lesaff/serverpilot-letsencrypt#if-things-go-wrong

Hope that helps

**Comment by debpalash** [comment]
thanks!
